# Generated by Django 5.2.8 on 2025-11-26 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='holyplace',
            old_name='longtude',
            new_name='longitude',
        ),
    ]
