# Generated by Django 5.2.8 on 2025-12-10 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='placeimage',
            name='public_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
